// Stable opportunity audit contract tests: synthetic monotonicity and safety caps.
const { execSync } = require('child_process'); const fs = require('fs'); const path = require('path');
const root = path.resolve(__dirname, '..'); const out = path.join(__dirname, '.verify-stable-audit'); fs.rmSync(out, { recursive: true, force: true }); fs.mkdirSync(out, { recursive: true });
const src = (p) => path.join(root, 'src', p);
execSync('npx tsc --ignoreConfig --module commonjs --target es2020 --skipLibCheck --outDir ' + JSON.stringify(out) + ' ' + [src('core/discountV2.ts'), src('core/opportunityV2.ts'), src('core/types/opportunity.ts'), src('core/liquidity.ts'), src('core/marketQuality.ts'), src('core/fees.ts'), src('core/profit.ts')].map(JSON.stringify).join(' '), { cwd: root, stdio: 'pipe', shell: true });
const { buildDiscountV2 } = require(path.join(out, 'core', 'discountV2.js')); const { buildOpportunityV2 } = require(path.join(out, 'core', 'opportunityV2.js'));
let p=0,f=0;const a=(n,o,x)=>{if(o){p++;console.log('PASS '+n)}else{f++;console.log('FAIL '+n+(x?` got=${x}`:''))}};
function input(price=10, state='STABLE') { return { item:'X', c5:{unitPrice:price,feeRatio:.01,availableQuantity:500,fetchedAt:1700000000000}, steam:{highestBuy:10,lowestSell:10.1,buyLevels:[{price:10,quantity:500,cumulativeQuantity:500}],sellLevels:[{price:10.1,quantity:500,cumulativeQuantity:500}],fetchedAt:1700000000000,quality:1},forecast:{p25:10,p50:11,p75:12,confidence:.9,marketState:state},quantity:10,now:1700000001000}; }
const results=[];for(const price of [10,9.5,9,8.5,8,7.5,7]){const d=buildDiscountV2(input(price));const o=buildOpportunityV2({item:'X',discount:d,market:{volume24h:5000,c5AvailableQuantity:500,highestBuy:10,lowestSell:10.1},risk:{marketState:'STABLE',cv:.03},forecast:{confidence:.9,direction:'UP'},feeModel:d.feeModel});results.push({price,d,o});}
for(let i=1;i<results.length;i++){a(`price decrease expected monotonic ${i}`,results[i].d.expected7d.discount<=results[i-1].d.expected7d.discount);a(`price decrease conservative monotonic ${i}`,results[i].d.conservative7d.discount<=results[i-1].d.conservative7d.discount);a(`price decrease discount score nondecreasing ${i}`,results[i].o.breakdown.discount>=results[i-1].o.breakdown.discount);a(`price decrease finite ${i}`,Number.isFinite(results[i].o.score));}
const lowInput=input(.18);lowInput.steam.highestBuy=.18;lowInput.steam.lowestSell=.19;const lowDiscount=buildDiscountV2(lowInput);const low=buildOpportunityV2({item:'low',discount:lowDiscount,market:{volume24h:5000,c5AvailableQuantity:500,highestBuy:.18,lowestSell:.19},risk:{marketState:'STABLE',cv:.03},forecast:{confidence:.9,direction:'UP'},feeModel:{kind:'approximate',exact:false}});a('low approximate fee cap',low.caps.includes('approximate_fee_low_price_cap_watch')&&['watch','avoid'].includes(low.decision));
const chaosD=buildDiscountV2(input(10,'CHAOS'));const chaos=buildOpportunityV2({item:'chaos',discount:chaosD,market:{volume24h:5000,c5AvailableQuantity:500,highestBuy:10,lowestSell:10.1},risk:{marketState:'CHAOS',cv:.03},forecast:{confidence:.9,direction:'UP'},feeModel:chaosD.feeModel});a('CHAOS cap',chaos.caps.includes('chaos_cap_watch')&&['watch','avoid'].includes(chaos.decision));
const capD=buildDiscountV2(input(10));const cap=buildOpportunityV2({item:'cap',discount:capD,market:{volume24h:5000,c5AvailableQuantity:500,highestBuy:10,lowestSell:10.1},risk:{marketState:'STABLE',cv:.03},forecast:{confidence:.9,direction:'UP'},feeModel:capD.feeModel});a('capacity positive',cap.suggestedMaxBudget<=capD.currentLiquidityCapacity.executableBudget);a('future warning retained',cap.warnings.includes('future_orderbook_not_predicted'));
for(const result of results){a(`result ${result.price} score range`,result.o.score>=0&&result.o.score<=100);a(`result ${result.price} decision known`,['avoid','watch','buy','excellent'].includes(result.o.decision));a(`result ${result.price} budget finite`,Number.isFinite(result.o.suggestedMaxBudget));a(`result ${result.price} breakdown finite`,Object.values(result.o.breakdown).every(Number.isFinite));a(`result ${result.price} gates array`,Array.isArray(result.o.hardGates));a(`result ${result.price} caps array`,Array.isArray(result.o.caps));a(`result ${result.price} no credentials`,!/token|cookie|app-key/i.test(JSON.stringify(result)));}
console.log('');console.log(`PASS ${p} / ${p+f}`);if(f>0)process.exitCode=1;else console.log('ALL STABLE OPPORTUNITY AUDIT ASSERTIONS PASSED');
